### ISSUE TITLE
As a player, I want to be able to make a move by choosing some square, so that I can place my symbol.

### ISSUE THREAD

**Issue by AriTechFH** [ic22b031/TicTacToe#1]
**Tasks:**

- [ ] Create a function which implements the described feater
- [ ] Write a unit test for the feature
- [ ] Merge feature to main

**Acceptance criteria:**
The player is able to make a move and can choose one square on the board, where the symbol of the player will be placed.

**Comment by AriTechFH** [comment]
![1](https://github.com/ic22b031/TicTacToe/assets/129103894/d896145c-146e-40ad-a0f5-d1ff7e3d3d54)
