### ISSUE TITLE
As a player, I want to be able to see the game, so that I can keep track of the moves made by both myself and my opponent.

### ISSUE THREAD

**Issue by ic22b031** [ic22b031/TicTacToe#2]
**Tasks:**

- [ ] Create a function which implements the descibed feature
- [ ] Write the unit test for the feature
- [ ] Merge feature to main

**Acceptance criteria:**

The player is able to make a move and can choose one square on the board, where the symbol of the player will be placed.

**Comment by ic22b031** [comment]
![grafik](https://github.com/ic22b031/TicTacToe/assets/129161152/a39125b0-41b6-40fc-b56c-6e1db055c1ae)
